version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports: []                 # keep port 11434 internal
    volumes:
      - ollama_models:/root/.ollama
    restart: unless-stopped

  annotator:
    build: ./annotator
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - MODEL_NAME=qwen3:4b
    depends_on:
      - ollama
volumes:
  ollama_models:
